server:
  port: 8080
  context: laboratorio

spring:
  profiles:
    active: develop
---
spring:
  profiles: develop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  conexao:
    jdbc-url: jdbc:postgresql://localhost:5432/conexao2
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
